import type { Category, Restaurant } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "food",
    name: "Food & Dining",
    emoji: "🍔",
    description: "Restaurants & fast food",
    count: "1,240+ options",
    href: "/restaurants",
  },
  {
    id: "grocery",
    name: "Grocery",
    emoji: "🛒",
    description: "Fresh produce & essentials",
    count: "3,800+ items",
    href: "/grocery",
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    emoji: "💊",
    description: "Medicine & health",
    count: "200+ pharmacies",
    href: "/pharmacy",
  },
  {
    id: "courier",
    name: "Courier",
    emoji: "📦",
    description: "Send anything, anywhere",
    count: "Same-day delivery",
    href: "/courier",
  },
  {
    id: "drinks",
    name: "Drinks",
    emoji: "🧃",
    description: "Beverages & smoothies",
    count: "500+ drinks",
    href: "/drinks",
  },
  {
    id: "express",
    name: "Fast Delivery",
    emoji: "⚡",
    description: "Under 20 minutes",
    count: "Lightning fast",
    href: "/express",
  },
];

export const FEATURED_RESTAURANTS: Restaurant[] = [
  {
    id: "1",
    name: "Burger Palace",
    description: "Juicy smash burgers and loaded fries",
    category: "Burgers",
    cuisine_type: "American · Fast food",
    image_url: "/images/restaurants/burger-palace.jpg",
    cover_url: "/images/restaurants/burger-palace-cover.jpg",
    rating: 4.8,
    review_count: 2341,
    delivery_time_min: 20,
    delivery_time_max: 30,
    delivery_fee: 1.99,
    min_order: 10,
    is_open: true,
    promo_label: "-20%",
    vendor_id: "v1",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Green Bowl",
    description: "Fresh, healthy salads and grain bowls",
    category: "Healthy",
    cuisine_type: "Healthy · Salads",
    image_url: "/images/restaurants/green-bowl.jpg",
    cover_url: "/images/restaurants/green-bowl-cover.jpg",
    rating: 4.9,
    review_count: 1890,
    delivery_time_min: 15,
    delivery_time_max: 25,
    delivery_fee: 0,
    min_order: 8,
    is_open: true,
    vendor_id: "v2",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Pizza Lab",
    description: "Artisan wood-fired pizzas since 2018",
    category: "Italian",
    cuisine_type: "Italian · Pizza",
    image_url: "/images/restaurants/pizza-lab.jpg",
    cover_url: "/images/restaurants/pizza-lab-cover.jpg",
    rating: 4.7,
    review_count: 3102,
    delivery_time_min: 25,
    delivery_time_max: 35,
    delivery_fee: 0.99,
    min_order: 12,
    is_open: true,
    promo_label: "Popular",
    vendor_id: "v3",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Sakura Sushi",
    description: "Authentic Japanese sushi and ramen",
    category: "Japanese",
    cuisine_type: "Japanese · Sushi",
    image_url: "/images/restaurants/sakura-sushi.jpg",
    cover_url: "/images/restaurants/sakura-sushi-cover.jpg",
    rating: 4.9,
    review_count: 987,
    delivery_time_min: 30,
    delivery_time_max: 40,
    delivery_fee: 2.49,
    min_order: 15,
    is_open: true,
    vendor_id: "v4",
    created_at: new Date().toISOString(),
  },
];

export const CUSTOM_REQUEST_ITEMS = [
  {
    icon: "🛒",
    name: "Groceries",
    description: "From any nearby store, customised to your list",
  },
  {
    icon: "💊",
    name: "Medicine",
    description: "Prescription or OTC, fast and discreet",
  },
  {
    icon: "💻",
    name: "Electronics",
    description: "Chargers, accessories, emergency gadgets",
  },
  {
    icon: "🎁",
    name: "Gifts",
    description: "Surprise someone special, anywhere nearby",
  },
  {
    icon: "🌸",
    name: "Flowers",
    description: "Fresh bouquets, same-hour delivery",
  },
  {
    icon: "📦",
    name: "Anything nearby",
    description: "If it exists nearby, we can bring it to you",
  },
];

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Restaurants", href: "/restaurants" },
  { label: "Grocery", href: "/grocery" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const STATS = [
  { num: "2M+", label: "Happy customers" },
  { num: "8K+", label: "Restaurant partners" },
  { num: "25 min", label: "Avg delivery time" },
];
